services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookiecms
      MYSQL_USER: cookiecms
      MYSQL_PASSWORD: cookiecms
    ports:
      - '34002:3306'
    volumes:
      - './:/application'
      - mysqld_socket:/run/mysqld
    command: --bind-address=0.0.0.0 && ./install_docker.sh

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'

#  webserver:
#    image: 'nginx:alpine'
#    container_name: nginx
#    working_dir: /application
#    volumes:
#      - './:/application'
#      - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
#    ports:
#      - '8080:80'

  frontend:
    image: 'node:latest'
    container_name: frontend
    working_dir: /application
    volumes:
      - './frontend:/application'
    ports:
      - '8000:8000'
    command: npm run dev

  
volumes:
  mysqld_socket:
