services:
  postgres:
    image: 'postgres:15'
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: cookiecms
      POSTGRES_USER: cookiecms
      POSTGRES_DB: cookiecms
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cookiecms_net

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cookiecms.com
      PGADMIN_DEFAULT_PASSWORD: cookiecms
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - cookiecms_net

  cookiecms:
    build: .
    container_name: cookiecms-app
    env_file:
      - .env
    ports:
      - '8000:8000'   # Используйте порт из .env
    depends_on:
      - postgres
    networks:
      - cookiecms_net

volumes:
  postgres_data:

networks:
  cookiecms_net:
    driver: bridge
