NameSite: cookiecms
securecode: "c8ENvF5zD5ThuM9mTwofBqMLGSEutUrztAeca3LFLKr3v9RRXeUnO7j7nskWbL2y"
ServiceApiToken: 2aiajDNUhW95HlSHcRDJK0psCBBGazwGWbnZi99Vcirb82SIEeNvxqKmqAJlwxuQ
MaxSavedSkins: 1
DEBUGLOG: 0 # 0 none, 1 requests, 2 full request with all
debugToken: 64c82dcb-c29d-4ff8-b6e6-b796a2672a1
domain: "http://localhost:3000"

# Duplicating audit from site to discord 
AuditSecret: 
  enabled: false
  url: https://discord.com/api/webhooks/1335629021349806080/LgTW8ar3URK41OTcMIsnsxSs3cTVeKZPtOu0x4xm138az2J4guy_VuBjwlmR4pVG2FWA
  spamming: "1335628917415088239"
  audit: 1335628983265394803 # main information change password change mail etc


database:
  host: "localhost"
  username: "cookiecms"
  pass: "cookiecms"
  db: "cookiecms"
  port: 34002

smtp:
  Host: "mail.coffeedev.dev"
  Username: "noreply@coffeedev.dev"
  Password: "45,chESIo,="
  SMTPSecure: true  # SSL requires secure: true
  Port: 465        # SSL Port


discord:
  enabled: true
  client_id: "1181148727826722816"
  secret_id: "kl-yQ-6Sa1LE23-o-QhLB_Ny9aSttURp"
  scopes:
    - identify
    - email
  redirect_url: "http://localhost:3000/callback"
  bot: ""
  guild_id: 0
  role: 0


permissions:
  0:
    - page.userlist
  1:
    - profile.changeusername
    - profile.changeskin
    - profile.changemail
    - profile.changepassword
    - profile.discord
  2:
    - profile.changeskinHD
  3:
    - admin.userslist
    - admin.useredit
    - admin.mailsend


servers:
  name:
    name:
    ip:
    port: